//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ArVisualisation
{
    [Serializable]
    public class MeshDataMsg : Message
    {
        public const string k_RosMessageName = "ar_visualisation_msgs/MeshData";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public int id;
        public Geometry.Vector3Msg[] vertices;
        public int[] triangles;

        public MeshDataMsg()
        {
            this.header = new Std.HeaderMsg();
            this.id = 0;
            this.vertices = new Geometry.Vector3Msg[0];
            this.triangles = new int[0];
        }

        public MeshDataMsg(Std.HeaderMsg header, int id, Geometry.Vector3Msg[] vertices, int[] triangles)
        {
            this.header = header;
            this.id = id;
            this.vertices = vertices;
            this.triangles = triangles;
        }

        public static MeshDataMsg Deserialize(MessageDeserializer deserializer) => new MeshDataMsg(deserializer);

        private MeshDataMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
            deserializer.Read(out this.vertices, Geometry.Vector3Msg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.triangles, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.id);
            serializer.WriteLength(this.vertices);
            serializer.Write(this.vertices);
            serializer.WriteLength(this.triangles);
            serializer.Write(this.triangles);
        }

        public override string ToString()
        {
            return "MeshDataMsg: " +
            "\nheader: " + header.ToString() +
            "\nid: " + id.ToString() +
            "\nvertices: " + System.String.Join(", ", vertices.ToList()) +
            "\ntriangles: " + System.String.Join(", ", triangles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
