//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ArVisualisation
{
    [Serializable]
    public class MeshesDataMsg : Message
    {
        public const string k_RosMessageName = "ar_visualisation_msgs/MeshesData";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public MeshDataMsg[] meshes;

        public MeshesDataMsg()
        {
            this.header = new Std.HeaderMsg();
            this.meshes = new MeshDataMsg[0];
        }

        public MeshesDataMsg(Std.HeaderMsg header, MeshDataMsg[] meshes)
        {
            this.header = header;
            this.meshes = meshes;
        }

        public static MeshesDataMsg Deserialize(MessageDeserializer deserializer) => new MeshesDataMsg(deserializer);

        private MeshesDataMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.meshes, MeshDataMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.meshes);
            serializer.Write(this.meshes);
        }

        public override string ToString()
        {
            return "MeshesDataMsg: " +
            "\nheader: " + header.ToString() +
            "\nmeshes: " + System.String.Join(", ", meshes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
